host: localhost
port: 9966
triggers:
  no_events:
    event: "*"
    metric: trailing_average_per_minute
    condition: ==0
    endpoint: http://example.com/events
  no_test_events:
    event: test_event
    metric: trailing_average_per_hour
    condition: <100
    endpoint: http://example.com/events
