port: 9966
streams:
  - /go/src/github.com/vail130/orinoco/artifacts/logs/
  - http://localhost:9966/streams/
  - ws://localhost:9966/streams/
triggers:
  -
    stream: test2
    metric: minute_to_date
    condition: ">10"
    endpoint: http://localhost:9966/streams/test2_stream_more_than_10_per_minute
