port: 9966
streams:
  -
    type: log
    path: /go/src/github.com/vail130/orinoco/artifacts/logs/
  -
    type: http
    url: http://localhost:9966/streams/
triggers:
  -
    stream: test2
    metric: minute_to_date
    condition: ">10"
    endpoint: http://localhost:9966/streams/test2_stream_more_than_10_per_minute
