port: 9966
streams:
  -
    type: s3
	access_key_id: AKIAIOSFODNN7EXAMPLE
	secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
	region: us-east-1
	bucket: orinoco
	prefix: streams
triggers:
  test2_stream_more_than_10_per_minute:
    stream: test2
    metric: minute_to_date
    condition: ">10"
    endpoint: http://localhost:9966/streams/test2_stream_more_than_10_per_minute
