port: 9966
min_batch_size: 100
max_batch_delay: 5
streams:
  -
    type: s3
    region: us-east-1
    bucket: orinoco-test
    prefix: "{{stream}}/{{year}}/{{month}}/{{day}}/"
triggers:
  test2_stream_more_than_10_per_minute:
    stream: test2
    metric: minute_to_date
    condition: ">10"
    endpoint: http://localhost:9966/streams/test2_stream_more_than_10_per_minute
