url: http://localhost:9966
triggers:
  test_litmus_stream_more_than_10_per_minute:
    event: test_litmus
    metric: minute_to_date
    condition: ">10"
    endpoint: http://localhost:9966/streams/test_litmus_stream_more_than_10_per_minute
