port: 9966
streams:
  -
    type: mysql
	user: user
	password: pass
	host: localhost
	port: 3306
	database: streams
triggers:
  test2_stream_more_than_10_per_minute:
    stream: test2
    metric: minute_to_date
    condition: ">10"
    endpoint: http://localhost:9966/streams/test2_stream_more_than_10_per_minute
